# Generated by Django 6.0.4 on 2026-05-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banque", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="client_banque",
            constraint=models.UniqueConstraint(
                fields=("nom", "prenom", "info_bancaire"),
                name="unique_client_banque_constraint",
            ),
        ),
    ]
