# Generated by Django 6.0.4 on 2026-05-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banque", "0005_remove_clientbanque_unique_client_banque_constraint_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="comptebancaire",
            constraint=models.UniqueConstraint(
                fields=("client_banque",), name="unique_CompteBancaire_constraint"
            ),
        ),
    ]
