# Generated by Django 6.0.4 on 2026-05-05 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banque', '0006_comptebancaire_unique_comptebancaire_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ClientBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('card_data', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='clientbanque',
            name='unique_client_banque_constraint',
        ),
        migrations.RemoveConstraint(
            model_name='comptebancaire',
            name='unique_CompteBancaire_constraint',
        ),
        migrations.AddConstraint(
            model_name='clientbank',
            constraint=models.UniqueConstraint(fields=('name', 'surname', 'card_data'), name='unique_client_banque_constraint'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='client_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banque.clientbank'),
        ),
        migrations.RemoveField(
            model_name='comptebancaire',
            name='client_banque',
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(fields=('client_bank',), name='unique_BankAccount_constraint'),
        ),
        migrations.DeleteModel(
            name='ClientBanque',
        ),
        migrations.DeleteModel(
            name='CompteBancaire',
        ),
    ]
