# Generated by Django 6.0.4 on 2026-04-20 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session_marchand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_objet", models.CharField(max_length=50)),
                ("prix_transaction", models.IntegerField()),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="gateway.token"
                    ),
                ),
            ],
        ),
    ]
