# Generated by Django 6.0.4 on 2026-04-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0002_session_marchand"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="nom",
            field=models.CharField(default="null", max_length=40),
        ),
        migrations.AddField(
            model_name="client",
            name="prenom",
            field=models.CharField(default="null", max_length=40),
        ),
    ]
