# Generated by Django 6.0.4 on 2026-04-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0004_alter_client_nom_alter_client_prenom"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="prix_transaction",
            field=models.IntegerField(default=0),
        ),
    ]
