# Generated by Django 6.0.4 on 2026-04-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0005_transaction_prix_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="prix_transaction",
            field=models.IntegerField(),
        ),
    ]
