# Generated by Django 6.0.4 on 2026-05-03 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0007_transaction_unique_payment_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='unique_payment_constraint',
        ),
    ]
