# Generated by Django 6.0.4 on 2026-05-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0013_remove_sessionmarchand_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionmarchand",
            name="idempotency_key",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
