# Generated by Django 6.0.4 on 2026-05-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0015_sessionmarchand_code_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionmarchand",
            name="code_id",
            field=models.UUIDField(null=True),
        ),
    ]
