# Generated by Django 6.0.4 on 2026-05-05 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0017_alter_sessionmarchand_code_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionmarchand',
            old_name='code_id',
            new_name='code_url',
        ),
    ]
