# Generated by Django 6.0.4 on 2026-05-05 07:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0019_transaction_created_at_transaction_idempotency_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='idempotency_key',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
