# Generated by Django 6.0.4 on 2026-05-05 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0020_alter_transaction_idempotency_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="token",
        ),
    ]
