# Generated by Django 6.0.4 on 2026-05-05 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0021_remove_transaction_token"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Token",
        ),
        migrations.RenameField(
            model_name="sessionmarchand",
            old_name="nom_objet",
            new_name="item_name",
        ),
    ]
