# Generated by Django 6.0.4 on 2026-05-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0022_delete_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionmarchand',
            old_name='prix_transaction',
            new_name='price_transaction',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='prix_transaction',
            new_name='price_transaction',
        ),
    ]
