# Generated by Django 6.0.4 on 2026-05-05 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0024_remove_carte_unique_card_constraint_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carte',
            new_name='Card',
        ),
    ]
