# Generated by Django 6.0.4 on 2026-05-06 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0025_rename_carte_card"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sessionmarchand",
            old_name="code_url",
            new_name="url_code",
        ),
    ]
