# Generated by Django 6.0.4 on 2026-04-10 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Objet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prix", models.IntegerField(default=0)),
                ("nom", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=100)),
                (
                    "objet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="site_marchand.objet",
                    ),
                ),
            ],
        ),
    ]
