# Generated by Django 6.0.4 on 2026-04-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_marchand", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="ammount",
            field=models.IntegerField(default=0),
        ),
    ]
