# Generated by Django 6.0.4 on 2026-04-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_marchand", "0003_session_delete_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objet",
            name="prix",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
