# Generated by Django 6.0.4 on 2026-05-05 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("site_marchand", "0005_session_created_at_session_idempotency_key_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Objet",
            new_name="Item",
        ),
        migrations.RenameField(
            model_name="session",
            old_name="objet",
            new_name="item",
        ),
    ]
