# Generated by Django 6.0.4 on 2026-05-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("site_marchand", "0006_rename_objet_item_rename_objet_session_item"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="nom",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="prix",
            new_name="price",
        ),
        migrations.RenameField(
            model_name="session",
            old_name="ammount",
            new_name="amount",
        ),
    ]
